---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Creates a VPC with 2 public and 2 private subnets in two availability zones, a caylent.com template'
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
    - Label:
        default: 'VPC Parameters'
      Parameters:
      - ClassB
Parameters:
  ClassB:
    Description: 'Class B of VPC (10.XXX.0.0/16)'
    Type: Number
    Default: 0
    ConstraintDescription: 'Must be in the range [0-255]'
    MinValue: 0
    MaxValue: 255
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
      CidrBlock: !Sub '10.${ClassB}.0.0/16'
      Tags:
      - Key: Name
        Value: !Sub '10.${ClassB}.0.0/16'
      - Key: caylent-id
        Value: Public
    Metadata:
      CAYLENT::NETWORK:
        uuid: ''
  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: VPC
      CidrBlock: !Sub '10.${ClassB}.1.0/24'
      Tags:
      - Key: Name
        Value: ''
      - Key: caylent-id
        Value: Public
      - Key: Network
        Value: Public
    Metadata:
      CAYLENT::SUBNET:
        uuid: ''
  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: VPC
      CidrBlock: !Sub '10.${ClassB}.2.0/24'
      Tags:
      - Key: Name
        Value: ''
      - Key: caylent-id
        Value: Public
      - Key: Network
        Value: Public
    Metadata:
      CAYLENT::SUBNET:
        uuid: ''
  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: VPC
      CidrBlock: !Sub '10.${ClassB}.3.0/24'
      Tags:
      - Key: Name
        Value: ''
      - Key: caylent-id
        Value: ''
      - Key: Network
        Value: Private
    Metadata:
      CAYLENT::SUBNET:
        uuid: ''
  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: VPC
      CidrBlock: !Sub '10.${ClassB}.4.0/24'
      Tags:
      - Key: Name
        Value: ''
      - Key: caylent-id
        Value: ''
      - Key: Network
        Value: Private
    Metadata:
      CAYLENT::SUBNET:
        uuid: ''
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
      - Key: Name
        Value: main-gateway
      - Key: Network
        Value: Public
  GatewayToInternet:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId:
        Ref: VPC
      InternetGatewayId:
        Ref: InternetGateway
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: VPC
      Tags:
      - Key: Name
        Value: public-route
      - Key: Network
        Value: Public
  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: GatewayToInternet
    Properties:
      RouteTableId:
        Ref: PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: InternetGateway
Outputs:
  VPCId:
    Description: VPCId of the newly created VPC
    Value:
      Ref: VPC
  PublicSubnet1:
    Description: SubnetId of the public subnet
    Value:
      Ref: PublicSubnet1
  PublicSubnet2:
    Description: SubnetId of the public subnet
    Value:
      Ref: PublicSubnet2
  PrivateSubnet1:
    Description: SubnetId of the public subnet
    Value:
      Ref: PrivateSubnet1
  PrivateSubnet2:
    Description: SubnetId of the public subnet
    Value:
      Ref: PrivateSubnet2
Metadata:
  CAYLENT::NETWORK-DEPLOYMENT:
    CAYLENT::ACTION:
      uuid: ''
